#!/usr/bin/env zsh
#
# Repacks a CBZ file to convert JPEG files to WEBP files

SOURCE=""
TARGET=""
DIR="$(mktemp -d)"

usage() {
	echo "cbz-repack-webp comic.cbz"
	exit 0
}

while getopts ":hq:o:d:" opt; do
    case $opt in
        h)
            usage
            exit
            ;;
        o)
            OUT_NAME=$OPTARG
            ;;
		\?)
			echo "Invalid option: $OPTARG" 1>&2
			exit 1
			;;
		:)
			echo "Invalid option: -$OPTARG requires an argument" 1>&2
			exit 1
		    ;;
    esac
done

SOURCE="${@[$OPTIND]}"

cleanup() {
	rm -rf $DIR
}

trap 'cleanup' ERR EXIT

if [ "$TARGET" = "" ]; then
	TARGET="$(basename "$SOURCE")"
	TARGET="${TARGET%.*}-webp.cbz"
fi

echo $TARGET

unzip "$SOURCE" -d "$DIR"

# Convert output images to webp
#for x in $(find "$DIR" -type f -exec file --mime-type {} \+ | awk -F: '{if ($2 ~/image\//) print $1}'); do
	#echo convert "$x" "${x%.*}.webp"
	#convert "$x" "${x%.*}.webp"
	#rm "$x"
#done

find "$DIR" -type f -exec file --mime-type {} \+ | awk -F: '{if ($2 ~/image\//) print $1}' | while read x; do
  echo "$x" >> $DIR/source-file-names
  echo echo convert "$x" "${x%.*}.webp" '&&' convert "$x" "${x%.*}.webp" >> $DIR/convert
done

#find $DIR -type f -exec file --mime-type {} \+ | awk -F: '{if ($2 ~/image\//) print $1}' > $DIR/image-file-names

NCPU="$(nproc)"
#cat $DIR/image-file-names | xargs -P $NCPU -I{} convert {} {}.webp
#cat $DIR/image-file-names | xargs -P $NCPU -I{} rm {}
#

cat $DIR/convert | xargs -P $NCPU -I{} sh -c {}

cat $DIR/source-file-names | while read x; do rm "$x"; done

rm $DIR/source-file-names $DIR/convert

# Create CBZ archive
echo zip --junk-paths "$TARGET" "$DIR/*"
zip --junk-paths "$TARGET" "$DIR"/*

