#!/usr/bin/env bash
#
# Repacks a CBZ file to convert page images to WEBP or AVIF files

SOURCE_CBZ=""
TARGET_CBZ=""
WORK_DIR="$(mktemp -d)"
RESIZE="100%"
PAGE_FORMAT=avif

# Number of images to convert in parallel
NCPU="$(nproc)"

usage() {
	echo "cbz-repack [-n parallelism] [-f avif|webp] [-r resize percentage] comic.cbz"
	exit 0
}

while getopts ":hq:o:r:f:n:" opt; do
    case $opt in
        h)
            usage
            exit
            ;;
	n)
	   NCPU="$OPTARG"
	   ;;
	f)
	   PAGE_FORMAT="$OPTARG"
	   ;;
	r)
	    RESIZE="$OPTARG"
	    ;;
        o)
            OUT_NAME="$OPTARG"
            ;;
		\?)
			echo "Invalid option: $OPTARG" 1>&2
			exit 1
			;;
		:)
			echo "Invalid option: -$OPTARG requires an argument" 1>&2
			exit 1
		    ;;
    esac
done

shift $(($OPTIND -1))

SOURCE_CBZ="$1"

cleanup() {
	rm -rf $WORK_DIR
}

trap 'cleanup' ERR EXIT

if [ "$TARGET_CBZ" = "" ]; then
	DIR="$(dirname "$SOURCE_CBZ")"
	FILE="$(basename "$SOURCE_CBZ")"
	TARGET_CBZ="$DIR/${FILE%.*}-$PAGE_FORMAT.cbz"
fi

echo $TARGET_CBZ

# Extract original CBZ to source directory
SOURCE_DIR="$WORK_DIR/source"
mkdir -p "$SOURCE_DIR"

# Construct repacked CBZ in target directory
TARGET_DIR="$WORK_DIR/target"
mkdir -p "$TARGET_DIR"

unzip "$SOURCE_CBZ" -d "$SOURCE_DIR"

# Find all images from CBZ archive. Use file mime type rather than file extension.
page_count=1
find "$SOURCE_DIR" -type f -exec file --mime-type {} \+ | awk -F: '{if ($2 ~/image\//) print $1}' | sort | while read x; do
  # sanitize file names.
  ext="${x##*.}"
  sane_page_name=$(printf "$SOURCE_DIR/page-%03d.$ext" "$page_count")

	if [[ "$x" != "$sane_page_name" ]]; then
  	mv "$x" "$sane_page_name"  
	fi

  let page_count=page_count+1

  # Append commands to execute to a file which can then be run through xargs to do the
  # image conversions in parallel
	target_page_name="${sane_page_name%.*}.$PAGE_FORMAT"
	target_page_name="$TARGET_DIR/$(basename "$target_page_name")"

  CMD="magick convert '$sane_page_name' -resize $RESIZE '$target_page_name'"
	echo echo "$CMD" '&&' "$CMD" >> $WORK_DIR/convert
done

# Run image file conversions in parallel
cat $WORK_DIR/convert | xargs -P $NCPU -I{} sh -c {}

# Copy ComicInfo.xml if it exists
if [ -f "$SOURCE_DIR/ComicInfo.xml" ]; then
	cp "$SOURCE_DIR/ComicInfo.xml" "$TARGET_DIR"
fi

# Create CBZ archive
echo zip --junk-paths "$TARGET_CBZ" "$TARGET_DIR/*"
zip --junk-paths "$TARGET_CBZ" "$TARGET_DIR"/*

