#!/usr/bin/env bash
#

DPI=400
PREFIX=page
MIDDLE_FORMAT=png
CBZ_NAME=""
DIR=$(mktemp -d)
PAGE_FORMAT=avif

usage() {
	echo "pdf-to-cbz [-d 400] [-i ppm|png] [-f jpeg|webp|avif] [-o comic.cbz] comic.pdf"
	exit 0
}

while getopts ":ho:d:i:f:" opt; do
	case $opt in
	    h)
		usage
	    exit
	    ;;
		d)
	    DPI=$OPTARG
	    ;;
		i)
	    MIDDLE_FORMAT=$OPTARG
		;;
		f)
		PAGE_FORMAT=$OPTARG
	    ;;
		o)
	    CBZ_NAME=$OPTARG
	    ;;
		\?)
	    echo "Invalid option: $OPTARG" 1>&2
	    exit 1
	    ;;
		:)
	    echo "Invalid option: -$OPTARG requires an argument" 1>&2
	    exit 1
	    ;;
    esac
done

if ! command -v pdfinfo >/dev/null 2>&1; then
  echo "Error: please install pdfinfo." 1>&2
  exit 1
fi

if ! command -v pdftoppm >/dev/null 2>&1; then
  echo "Error: please install pdftoppm." 1>&2
  exit 1
fi

#if ! command -v pv >/dev/null 2>&1; then
  #echo "Error: please install pv (progress viewer)." 1>&2
  #exit 1
#fi

if ! command -v magick >/dev/null 2>&1; then
  echo "Error: please install ImageMagic." 1>&2
  exit 1
fi

shift $((OPTIND-1))

#echo $1
PDF="$1"

# Count PDF pages
PAGE_COUNT=$(pdfinfo "$PDF" | awk '/^Pages:/ {print $2}')

cleanup() {
    rm -rf $DIR
}

progress_bar() {
    while read x; do echo .; done
    #pv -c -l -p -t -e -s $PAGE_COUNT -N $1 
}

convert_page() {
    OUT="${1%.*}.$PAGE_FORMAT"
    magick convert "$1" "$OUT"
    echo "$OUT"
}

export -f convert_page

trap 'cleanup' ERR EXIT

if [ "$CBZ_NAME" = "" ]; then
	CBZ_NAME="$(basename "$PDF")"
	CBZ_NAME="$(dirname "$PDF")/${CBZ_NAME%.*}.cbz"
fi

echo "PDF: $PDF" 1>&2
echo "Pages: $PAGE_COUNT" 1>&2
echo "Working directory: $DIR" 1>&2
echo "Intermediate file format: $MIDDLE_FORMAT" 1>&2

NCPU=$(nproc)

# Extract pages as images.
case $MIDDLE_FORMAT in
	png)
		pdftoppm -r $DPI -progress -png $EXPORT_ARG "$PDF" "$DIR/$PREFIX" 2>&1 
		;;
	ppm)
		pdftoppm -r $DPI -progress $EXPORT_ARG "$PDF" "$DIR/$PREFIX" 2>&1 
		;;
esac

# Convert output images to webp
find $DIR -regex '.*\.png' -o -regex '.*\.ppm' | while read x; do convert_page "$x"; done | progress_bar WEBP >/dev/null

# Create CBZ archive
zip --junk-paths "$CBZ_NAME" $DIR/*.$PAGE_FORMAT | progress_bar ZIP >/dev/null

