# SPDX-FileCopyrightText: © 2024 David Bliss <vivid.map6767@davidbliss.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "CBZ Tools"
SPDX-PackageSupplier = "David Bliss <vivid.map6767@davidbliss.me>"
SPDX-PackageDownloadLocation = "https://github.com/blissd/cbz-tools"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "David Bliss <vivid.map6767@davidbliss.me>"
SPDX-License-Identifier = "GFDL-1.3-or-later"
